name: Hello World Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
